import re

# Read English file
with open('english/ddm_l_english.yml', 'r', encoding='utf-8-sig') as f:
    lines = f.readlines()

# Dict of manual translations for key UI, Decision, Event, and Interaction keys
d = {}

def add(k, v):
    d[k] = v

# --- 1. GAME RULES, DECISIONS & INTERACTIONS ---
add("game_rule_category_ddm", "宗族领地管理器")
add("decision_group_type_ddm_domain_management_group", "宗族领地管理")
add("ddm_domain_management_group", "宗族领地管理")

add("ddm_open_manager_decision", "管理宗族领地")
add("ddm_open_manager_decision_desc", "开启常设宗族行政机构，统一管理头衔、继承、军事基础设施和家族政策。")
add("ddm_open_manager_decision_tooltip", "打开宗族领地公署。各项事务已按部门分组，以便连续处理多项任务而无需重复打开决策。")
add("ddm_open_manager_decision_confirm", "进入公署")

add("ddm_assess_dynasty_member_interaction", "评估宗族价值")
add("ddm_assess_dynasty_member_interaction_desc", "让内廷评估该宗族成员的血统、能力、性情、忠诚度以及在家族中的地位。")
add("ddm_protect_dynasty_member_interaction", "保护免受自动化管理")
add("ddm_protect_dynasty_member_interaction_desc", "将该宗族成员排除在自动化整理与领地分配行动之外。")
add("ddm_unprotect_dynasty_member_interaction", "取消自动化保护")
add("ddm_unprotect_dynasty_member_interaction_desc", "允许领地管理器再次对该宗族成员进行常规考量。")
add("ddm_favor_for_land_interaction", "优先分封土地")
add("ddm_favor_for_land_interaction_desc", "指示宗族公署在有合适头衔可用时强烈优先考虑此人。")
add("ddm_never_grant_land_interaction", "绝不分封土地")
add("ddm_never_grant_land_interaction_desc", "禁止自动领地管理器向此人授予任何头衔。")
add("ddm_clear_land_preference_interaction", "清除土地偏好")
add("ddm_clear_land_preference_interaction_desc", "取消在土地分配系统中对此人的特殊优先或排除指令。")
add("ddm_protect_holding_interaction", "保护个人地产")
add("ddm_protect_holding_interaction_desc", "选择我个人持有的一处伯爵领或次级男爵领并锁定在受保护领地中。过剩分配器绝不会分出手动受保护的地产。此头衔选择器可从我自己的肖像或当前玩家继承人处打开；点击的人物并非接收者。")
add("ddm_unprotect_holding_interaction", "取消保护个人地产")
add("ddm_unprotect_holding_interaction_desc", "选择我手动受保护的一处地产，恢复其常规优化考量。头衔选择器可从我的肖像或当前玩家继承人处打开。")
add("ddm_prioritize_holding_for_distribution_interaction", "优先分出地产")
add("ddm_prioritize_holding_for_distribution_interaction_desc", "选择我的一处地产并将其标记为预定放弃土地。除非是首都或后来受到保护，否则过剩管理器会在让出优化器选定的土地之前先放弃此地产。")
add("ddm_clear_holding_distribution_priority_interaction", "清除地产分出优先级")
add("ddm_clear_holding_distribution_priority_interaction_desc", "选择先前标记为优先分出的地产并移除该指令。")
add("ddm_reserve_title_for_recipient_interaction", "为候选人预留头衔")
add("ddm_reserve_title_for_recipient_interaction_desc", "选择我的一处直属头衔并为该人物预留。有效的预留会在普通评分之前处理。王室领地保护、首都、宗教头衔限制、阶衔限制以及CK3常规分封合法性依然适用。")
add("ddm_clear_title_reservation_interaction", "清除头衔预留")
add("ddm_clear_title_reservation_interaction_desc", "选择目前为此人物预留的头衔，恢复其普通按分分配状态。")

add("ddm_manager.close", "到此为止。")
add("ddm_manager.back", "返回。")
add("ddm_manager.main", "返回主公署。")
add("ddm_manager.continue_realm", "继续处理领地与头衔。")
add("ddm_manager.continue_dynasty", "继续处理宗族与继承。")
add("ddm_manager.continue_military", "继续处理军事与建设。")

# --- 2. MAIN COMPACT OFFICE & REALM EVENTS (0001 - 1022) ---
add("ddm_manager.0001.t", "宗族领地公署")
add("ddm_manager.0001.desc", "公署已划分为多个部门，不必将所有指令挤在一个页面。我的个人直辖领为 #V [GetPlayer.GetDomainSize]#! 处地产，直辖上限为 #V [GetPlayer.GetDomainLimit]#!。我的在世宗族人数为 #V [GetPlayer.MakeScope.Var('ddm_dash_living_dynasty').GetValue|0]#!，其中 #V [GetPlayer.MakeScope.Var('ddm_dash_safe_county_recipients').GetValue|0]#! 人目前符合伯爵领受封规则。\n\n#help 请选择一个部门。现在各项操作都会返回相应的部门而不是关闭界面，因此可以连续下达多条相关指令。#!")
add("ddm_manager.0001.a", "领地与头衔")
add("ddm_manager.0001.a.flavor", "分配地产、组织等级体系、收回土地，或准确检查阻碍领地计划的原因。")
add("ddm_manager.0001.b", "宗族与继承")
add("ddm_manager.0001.b.flavor", "围绕继承进行规划、审查家族、刷新同盟，并在继承后清理领地。")
add("ddm_manager.0001.c", "军事与建设")
add("ddm_manager.0001.c.flavor", "询问军务公署直辖领支持何种军队，并在全领地范围内实施建设方案，无需逐个点击地产。")
add("ddm_manager.0001.d", "规则与偏好")
add("ddm_manager.0001.d.flavor", "更改土地、继承、同盟、清理以及国库储备政策。")

add("ddm_manager.1000.t", "领地与头衔")
add("ddm_manager.1000.desc", "我的个人核心领地最先获得保护。任何过剩地产随后会根据感知宣称、领土正统性、能力、政治安全和现有实力，对所有符合条件的宗族成员进行评估。继承状况可以修正评分，但绝不决定受封候选池。")
add("ddm_manager.1000.a", "执行完整的宗族交接安置。")
add("ddm_manager.1000.a.flavor", "收回符合条件的非宗族头衔，仅放弃我不需要的个人地产，然后将更高级别的头衔置于连贯的宗族层级中。")
add("ddm_manager.1000.b", "仅分配我的过剩地产。")
add("ddm_manager.1000.b.flavor", "在首次授予前，强制要求我归类任何从未审查过的个人持有伯爵领或次级男爵领：保留、分出，或由公署决定。随后一旦实际直辖领达到上限即停止。")
add("ddm_manager.1000.c", "组织公爵领与王国。")
add("ddm_manager.1000.c.flavor", "在可能的情况下提拔合适的本地宗族成员，同时避免过度堆砌危险的个人实力。")
add("ddm_manager.1000.d", "收回非宗族土地。")
add("ddm_manager.1000.d.flavor", "从非宗族统治者手中收回我麾下符合条件的头衔，并立即安置由此产生的过剩土地。")
add("ddm_manager.1000.e", "预览领地计划与阻碍因素。")
add("ddm_manager.1000.e.flavor", "不做出任何头衔变更。展示管理器可以分配的内容、可能停止的原因，以及最先放弃的地产。")

add("ddm_manager.0100.t", "领地已安置")
add("ddm_manager.0100.desc", "文书官完成了安置。从非宗族手中收回了 #V [GetPlayer.MakeScope.Var('ddm_last_titles_reclaimed').GetValue|0]#! 个头衔，分配了 #V [GetPlayer.MakeScope.Var('ddm_last_baronies_granted').GetValue|0]#! 个次级男爵领和 #V [GetPlayer.MakeScope.Var('ddm_last_counties_granted').GetValue|0]#! 个伯爵领，安置了 #V [GetPlayer.MakeScope.Var('ddm_last_duchies_granted').GetValue|0]#! 个公爵领、#V [GetPlayer.MakeScope.Var('ddm_last_kingdoms_granted').GetValue|0]#! 个王国和 #V [GetPlayer.MakeScope.Var('ddm_last_empires_granted').GetValue|0]#! 个帝国。\n\n#help 如果我仍超出直辖上限，请使用预览与阻碍报告。它能区分是缺乏可分配地产还是缺乏安全的受封者。#!")
add("ddm_manager.0101.t", "过剩地产已分配")
add("ddm_manager.0101.desc", "公署开始时在我选定的个人领地之外有 #V [GetPlayer.MakeScope.Var('ddm_last_distribution_start_surplus').GetValue|0]#! 处地产，并排队了 #V [GetPlayer.MakeScope.Var('ddm_last_titles_queued').GetValue|0]#! 处可转让地产。授予了 #V [GetPlayer.MakeScope.Var('ddm_last_baronies_granted').GetValue|0]#! 个次级男爵领和 #V [GetPlayer.MakeScope.Var('ddm_last_counties_granted').GetValue|0]#! 个伯爵领，随后安置了 #V [GetPlayer.MakeScope.Var('ddm_last_duchies_granted').GetValue|0]#! 个公爵领、#V [GetPlayer.MakeScope.Var('ddm_last_kingdoms_granted').GetValue|0]#! 个王国和 #V [GetPlayer.MakeScope.Var('ddm_last_empires_granted').GetValue|0]#! 个帝国。我现在个人持有 #V [GetPlayer.GetDomainSize]#! 处地产；我的受保护领地目标为 #V [GetPlayer.MakeScope.Var('ddm_protected_domain_target').GetValue|0]#!，而原版允许最多 #V [GetPlayer.GetDomainLimit]#! 处。\n\n在紧邻我最高头衔之下的阶衔，公署为我保留了 #V [GetPlayer.MakeScope.Var('ddm_last_top_rank_retained').GetValue|0]#! 个头衔——按每持有伯爵领军事实力计算最强的 40%——并将其余部分通过宗族层级分配。\n\n#help 每人没有固定的伯爵领配额。每个合法合规的宗族成员都可以继续接收土地；直辖规模、同批次封赏和过高军事实力会降低正统性评分，而不会耗尽受封者池。运行仅在我选定的受保护领地目标处或没有未受保护头衔可以机械转让时结束。#!\n\n如果仍有剩余，公署在本次运行后记录了 #V [GetPlayer.MakeScope.Var('ddm_last_baronies_left').GetValue|0]#! 个排队的次级男爵领和 #V [GetPlayer.MakeScope.Var('ddm_last_titles_left').GetValue|0]#! 个排队的伯爵领。")
add("ddm_manager.0101.stalled", "\n\n#N 部分未受保护的地产无法机械转让。#! 公署并非有意在原版直辖上限处停止。如果我的个人直辖领仍高于受保护目标，这些属于实际的转让/资格失败，应当予以检查。")
add("ddm_manager.0102.t", "高级头衔已排序")
add("ddm_manager.0102.desc", "公署安置了 #V [GetPlayer.MakeScope.Var('ddm_last_duchies_granted').GetValue|0]#! 个公爵领、#V [GetPlayer.MakeScope.Var('ddm_last_kingdoms_granted').GetValue|0]#! 个王国和 #V [GetPlayer.MakeScope.Var('ddm_last_empires_granted').GetValue|0]#! 个帝国。直接位于我自己阶衔之下的头衔享有特殊处理：我保留按每伯爵领军事实力计算最强的 40%，其余 60% 分配给领地正统性最高的宗族成员。较低的中间头衔则向下按层级组织。")
add("ddm_manager.0103.t", "非宗族头衔已收回")
add("ddm_manager.0103.desc", "公署从宗族之外收回了 #V [GetPlayer.MakeScope.Var('ddm_last_titles_reclaimed').GetValue|0]#! 个符合条件的头衔，随后根据现行领地规则重新分配了个人过剩土地。")

add("ddm_manager.1010.t", "领地计划：预览与阻碍因素")
add("ddm_manager.1010.desc", "预览模拟了全宗族正统统治者分配。它将受保护的个人地产与可分配的过剩土地区分开来，并展示是否存在机械安全的宗族受封者。继承信号人物仅作为修正因子或用于狭窄的原版封赏门槛绕过。")
add("ddm_manager.1010.status_ok", "\n#P 无需领地行动：我已处于或低于直辖上限。#!")
add("ddm_manager.1010.status_stale_plan", "\n#N 需要玩家决策：我当前的直辖上限与上次记录个人领地计划时的上限不一致。DDM将重新开始逐个地产审查，而不是猜测哪些额外地产应当进入或离开我的核心领地。#!")
add("ddm_manager.1010.status_unreviewed", "\n#N 需要玩家决策：我仍有 #V [GetPlayer.MakeScope.Var('ddm_dash_unclassified_domain_count').GetValue|0]#! 处个人持有的地产从未进行过归类。在明确选择保留、分出或由公署决定之前，DDM不会放弃其中任何一处。#!")
add("ddm_manager.1010.status_too_many_locks", "\n#N 主要阻碍：硬性保护的地产数量超出了直辖上限的支持能力。在期望管理器达到上限前，请至少移除一个手动锁定或禁用绝对核心保护。#!")
add("ddm_manager.1010.status_no_recipient", "\n#N 主要阻碍：符合条件的宗族中目前没有合法安全的受封者来接收此过剩头衔。请检查宗族资格、性别法匹配、领地完整性和实力安全设置。#!")
add("ddm_manager.1010.status_no_holding", "\n#N 主要阻碍：根据当前核心规则，没有个人持有的男爵领或伯爵领可合法分配。绝对核心保护可能是原因所在。#!")
add("ddm_manager.1010.status_ready", "\n#P 公署拥有可分配土地。#! 每个头衔都将依据家族重视、领地正统性、能力、安全性和现有实力，分配给当时评分最高的合格宗族成员。继承仅作为修正因子。")
add("ddm_manager.1010.next_barony", "\n优化器接下来将放弃的次级男爵领：#V [ddm_preview_next_barony.GetName]#!。")
add("ddm_manager.1010.next_county", "\n优化器接下来将放弃的伯爵领：#V [ddm_preview_next_county.GetName]#!。")
add("ddm_manager.1010.best_heir", "\n当前最高顺位合法继承人：#V [ddm_preview_best_heir.GetName]#!。")
add("ddm_manager.1010.second_heir", " 下一位合法继承人候选：#V [ddm_preview_second_heir.GetName]#!。")
add("ddm_manager.1010.a", "立即执行过剩领地计划。")
add("ddm_manager.1010.a.flavor", "如果我有任何未审查的地产，在封赏前询问如何处理。随后遵循我的受保护核心与分出优先级，优先使用合法分割继承人，并在达到实际直辖上限时停止。")
add("ddm_manager.1010.b", "配置受保护领地。")
add("ddm_manager.1010.b.flavor", "逐一选择我希望保留的准确地产。优化器可以提供建议，但绝不再用其判断替代玩家的明确选择。")

add("ddm_manager.1020.t", "选择我的个人领地")
add("ddm_manager.1020.desc", "除非我明确告知，否则公署无法得知我个人关心哪些土地。因此本界面将 #V 我的命令#! 与 #V 优化器的建议#! 区分开来。\n\n#P 按我命令保护：#! [GetPlayer.MakeScope.Var('ddm_dash_manual_core_count').GetValue|0]\n#N 优先放弃：#! [GetPlayer.MakeScope.Var('ddm_dash_manual_shed_count').GetValue|0]\n#V 明确交由公署：#! [GetPlayer.MakeScope.Var('ddm_dash_manual_neutral_count').GetValue|0]\n#V 公署推荐核心：#! [GetPlayer.MakeScope.Var('ddm_dash_auto_core_count').GetValue|0]\n\n#help 我的首都领地始终受保护。最安全的方法是点击第一个按钮：DDM将展示每一处其他个人持有的伯爵领或次级男爵领，并询问我保留、分出还是由公署决定。如果我保护的地产数量恰好等于直辖上限，剩余所有未归类地产将自动标记为待分出。新征服的地产没有归类，因此下一次过剩分配运行会在分封前询问我。#!")
add("ddm_manager.1020.a", "逐个选择我的地产。")
add("ddm_manager.1020.a.flavor", "重置旧计划并梳理我的个人领地。由我——而非优化器——决定哪些地产是神圣不可侵犯的、可放弃的，或留给行政裁量。")
add("ddm_manager.1020.b", "接受公署推荐的核心。")
add("ddm_manager.1020.b.flavor", "明确锁定优化器当前最佳地产至我的直辖上限。这是玩家指令，而非自动假设。")
add("ddm_manager.1020.c", "保护首都公爵领伯爵领。")
add("ddm_manager.1020.c.flavor", "将我首都法理公爵领内所有个人持有的伯爵领添加到受保护核心中。")
add("ddm_manager.1020.d", "保护常备军驻扎伯爵领。")
add("ddm_manager.1020.d.flavor", "将目前驻扎了我常备军军团的所有个人持有伯爵领添加到受保护核心中。")
add("ddm_manager.1020.e", "重置所有地产选择。")
add("ddm_manager.1020.e.flavor", "擦除所有保留、分出和交由公署决定的归类，仅保留首都的自动保护。下一次过剩分配运行将再次询问我。")

add("ddm_manager.1021.t", "保留还是放弃 [scope:ddm_core_candidate.GetName]？")
add("ddm_manager.1021.desc", "这是对 #V [scope:ddm_core_candidate.GetName]#! 的明确命令，而非推测的偏好。\n\n迄今已保护：#V [GetPlayer.MakeScope.Var('ddm_dash_manual_core_count').GetValue|0]#! / 当前直辖上限 #V [GetPlayer.GetDomainLimit]#!。\n标记优先放弃：#V [GetPlayer.MakeScope.Var('ddm_dash_manual_shed_count').GetValue|0]#!。\n交由公署裁量：#V [GetPlayer.MakeScope.Var('ddm_dash_manual_neutral_count').GetValue|0]#!。\n\n#help 保留会使该地产绝对不可用于自动分配。分出会将其推至过剩队列最前列。由公署决定记录了我特意授权此地产；此时DDM方可利用发展度、建筑、常备军驻扎及其他留存因子来决定其命运。#!")
add("ddm_manager.1021.recommend_keep", "\n#P 公署建议：保留。#! 根据当前留存公式，该地产位列推荐个人核心之内。")
add("ddm_manager.1021.recommend_shed", "\n#N 公署建议：可放弃。#! 根据当前留存公式，该地产处于推荐个人核心之外。")
add("ddm_manager.1021.maa", "\n#V 军事备注：#! 我的一个常备军军团驻扎在此。")
add("ddm_manager.1021.capital_duchy", "\n#V 核心区域备注：#! 该伯爵领位于我首都的法理公爵领内。")
add("ddm_manager.1021.a", "保留 [scope:ddm_core_candidate.GetName]。")
add("ddm_manager.1021.a.flavor", "硬性保护此地产。在我持有期间，DDM绝不可将其自动授予他人。")
add("ddm_manager.1021.b", "分出 [scope:ddm_core_candidate.GetName]。")
add("ddm_manager.1021.b.flavor", "将此地产标记为优先放弃。如果我仍超出直辖上限，DDM应在让出中立地产之前先放弃它。")
add("ddm_manager.1021.c", "由公署决定此地产。")
add("ddm_manager.1021.c.flavor", "记录我特意将此地产的命运授权给优化器。")
add("ddm_manager.1021.d", "由公署决定所有剩余地产。")
add("ddm_manager.1021.d.flavor", "停止逐一审查。我未明确保护或命令分出的所有内容都将变为中立，并由优化器评分。")

add("ddm_manager.1022.t", "我的领地命令已记录")
add("ddm_manager.1022.desc", "公署现在拥有了明确的指令，无需再进行猜测。\n\n#P 受保护地产：#! #V [GetPlayer.MakeScope.Var('ddm_dash_manual_core_count').GetValue|0]#!\n#N 优先放弃地产：#! #V [GetPlayer.MakeScope.Var('ddm_dash_manual_shed_count').GetValue|0]#!\n#V 授权给优化器：#! #V [GetPlayer.MakeScope.Var('ddm_dash_manual_neutral_count').GetValue|0]#!\n当前直辖：#V [GetPlayer.GetDomainSize]#!/#V [GetPlayer.GetDomainLimit]#!。\n\n#help 分配器现在遵循以下命令层级：(1) 绝不让出明确受保护的地产；(2) 首先放弃明确标记为牺牲的地产；(3) 仅对我明确授权的地产，使用优化器的留存公式。新持有的地产为未归类状态，将在下次直接过剩分配前触发此审查。#!")
add("ddm_manager.1022.a", "继续执行已记录的领地行动。")
add("ddm_manager.1022.a.flavor", "使用我刚记录的个人领地命令，然后恢复引导我来到这里的分配或完整安置行动。")
add("ddm_manager.1022.b", "在封赏前预览计划。")
add("ddm_manager.1022.b.flavor", "带着这些已记录的准确地产命令返回预览与阻碍因素。")
add("ddm_manager.1022.c", "再次审查每一处地产。")
add("ddm_manager.1022.c.flavor", "擦除计划并重新开始逐一领地审查。")

print("Stage 1 translation table built. Total keys:", len(d))
